use_frameworks!

target 'SwiftRubySyntax_Example' do
  pod 'SwiftRubySyntax', :path => '../'

  target 'SwiftRubySyntax_Tests' do
    inherit! :search_paths

  pod 'Quick', '~> 1.0.0'
  pod 'Nimble', '~> 5.1.1'
  pod 'FBSnapshotTestCase'
  pod 'Nimble-Snapshots'
  end
end
